;'use strict';
/* browsers with no console */
if(typeof console == 'undefined'){var console={log:function(m){}};}
/* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray */
if(!Array.isArray){console.log('Polyfill Array.isArray');Array.isArray = function(arg){return Object.prototype.toString.call(arg)==='[object Array]';};}
/* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter */
if(!Array.prototype.filter){console.log('Polyfill Array.prototype.filter');Array.prototype.filter=function(fun){if(this===void 0||this===null){throw new TypeError();}var t=Object(this);var len=t.length>>>0;if(typeof fun !=='function'){throw new TypeError();}var res=[];var thisArg=arguments.length>=2?arguments[1]:void 0;for(var i=0;i<len;i++){if(i in t){var val=t[i];if(fun.call(thisArg,val,i,t)){res.push(val);}}}return res;};}
/* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf */
if(!Array.prototype.indexOf){console.log('Polyfill Array.prototype.indexOf');Array.prototype.indexOf=function(searchElement,fromIndex){var k;if(this==null){throw new TypeError('"this" is null or not defined');}var o=Object(this);var len=o.length>>>0;if(len===0){return -1;}var n=+fromIndex||0;if(Math.abs(n)===Infinity){n=0;}if(n>=len){return -1;}k=Math.max(n>=0?n:len - Math.abs(n),0);while(k<len){if(k in o && o[k]===searchElement){return k;}k++;}return -1;};}
/* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice */
(function(){var _slice=Array.prototype.slice;try{_slice.call(document.documentElement);}catch(e){console.log('Polyfill Array.prototype.slice');Array.prototype.slice=function(begin,end){end=(typeof end !=='undefined')?end:this.length;if(Object.prototype.toString.call(this)==='[object Array]'){return _slice.call(this,begin,end);}var i,cloned=[],size,len=this.length;var start=begin || 0;start=(start>=0)?start:Math.max(0,len+start);var upTo=(typeof end=='number')?Math.min(end,len):len;if(end<0){upTo=len+end;}size=upTo - start;if(size>0){cloned=new Array(size);if(this.charAt){for(i=0;i<size;i++){cloned[i]=this.charAt(start+i);}}else{for(i=0;i<size;i++){cloned[i]=this[start+i];}}}return cloned;};}}());
/* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON */
if(!window.JSON){console.log('Polyfill JSON');window.JSON={parse:function(sJSON){return eval('('+sJSON+')');},stringify:(function(){var toString=Object.prototype.toString;var isArray=Array.isArray||function(a){return toString.call(a)==='[object Array]';};var escMap={'"':'\\"','\\':'\\\\','\b':'\\b','\f':'\\f','\n':'\\n','\r':'\\r','\t':'\\t'};var escFunc=function(m){return escMap[m]||'\\u'+(m.charCodeAt(0)+0x10000).toString(16).substr(1);};var escRE=/[\\"\u0000-\u001F\u2028\u2029]/g;return function stringify(value){if(value==null){return 'null';}else if(typeof value==='number'){return isFinite(value)?value.toString():'null';}else if(typeof value==='boolean'){return value.toString();}else if(typeof value==='object'){if(typeof value.toJSON==='function'){return stringify(value.toJSON());}else if(isArray(value)){var res='[';for(var i=0;i<value.length;i++)res+=(i?',':'')+stringify(value[i]);return res+']';}else if(toString.call(value)==='[object Object]'){var tmp=[];for(var k in value){if(value.hasOwnProperty(k))tmp.push(stringify(k)+':'+stringify(value[k]));}return '{'+tmp.join(',')+'}';}}return '"'+value.toString().replace(escRE,escFunc)+'"';};})()};}
/* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString */
if(!Date.prototype.toISOString){console.log('Polyfill Date.prototype.toISOString');(function(){function pad(number){if(number<10){return '0'+number;}return number;}Date.prototype.toISOString=function(){return this.getUTCFullYear()+'-'+pad(this.getUTCMonth()+1)+'-'+pad(this.getUTCDate())+'T'+pad(this.getUTCHours())+':'+pad(this.getUTCMinutes())+':'+pad(this.getUTCSeconds())+'.'+(this.getUTCMilliseconds()/1000).toFixed(3).slice(2, 5)+'Z';};}());}
/* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim */
if(!String.prototype.trim){console.log('Polyfill String.prototype.trim');String.prototype.trim=function(){return this.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,'');};}
/* SVG feature detection */
(function(window,document,undefined){var supports=!!document.createElementNS&&!!document.createElementNS('http://www.w3.org/2000/svg','svg').createSVGRect;if(!supports){console.log('Polyfill SVG not supported');return};document.documentElement.className+=(document.documentElement.className?' ':'')+'svg'})(window,document);